baseURL = 'https://mabsproject.org'
languageCode = 'en-us'
title = 'Maintainable Affordable Buildable Sustainable'
theme = "hugo-theme-learn"
publishDir = "docs"

[params]
description = "Make building a home pratical"
showVisitedLinks = true
disableMermaid = false
themeVariant = "blue"
customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"

[outputs]
home = [ "HTML", "RSS", "JSON"]
